server:
  port: 9090

---
spring:
  config:
    activate:
      on-profile: docker
eureka:
  client:
    serviceUrl:
      defaultZone: http://pc-discovery-server.pc-discovery-server.svc:8761/eureka/
